### ISSUE TITLE
[FEATURE] Support the creation of role libraries

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#302]
**Is your feature request related to a problem? Please describe.**
As a user, I want to create a library of roles that I can use in use case definitions. This would allow me to centralise the creation and management of reusable roles, without them being added to the curated role list as part of the ace-box.

**Describe the solution you'd like**
Have a role available that allows loading external repositories as such they become available to be used.

E.g.:
```
- include_role:
    name: "load-external-library"
  vars:
    source: "https://github.com/dynatrace-ace/ace-box-lib-apps.git"
```
