### ISSUE TITLE
[BUG] DT metrics API changed unit for certain metrics

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#347]
**Describe the bug**
Certain metrics are returned in a different unit which is causing quality gates to fail:

![Cursor_and_Cloud_Automation](https://user-images.githubusercontent.com/9797800/201858585-b7fef49b-73e3-4693-b035-f465006ad21c.png)

In this case the response time metric is now in microseconds as opposed to milliseconds (25286 vs 250,286).

**To Reproduce**
1. Run any OOTB demo Release Validation/QG flow
2. See the "Response Time 95th Percentile" fail

**Expected behavior**
Quality Gate would pass

**Comment by kristofre** [comment]
To bypass the issue, open up the `cloudautomation/slo.yaml` and `cloudautomation/slo_appsec.yaml` in gitea/gitlab and change the unit to verify against:

```yaml
objectives:
  - sli: "response_time_p95"
    displayName: "Response Time 95th Percentile"
    key_sli: false
    pass:             # pass if (relative change <= 10% AND absolute value is < 600ms)
      - criteria:
          - "<=+10%"  # relative values require a prefixed sign (plus or minus)
          - "<800000"    # absolute values only require a logical operator
    warning:          # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=1000000"
    weight: 1
```
