### ISSUE TITLE
[BUG] Incompatibility between microk8s and operator default

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#740]
The default setting (deployed in `applicationMonitoring` mode and on version `1.3.0-rc.0` stops all of our demo use cases from being deployed as they are on `microk8s`

The operator needs to be deployed as follows for our use cases to deploy:

```
- include_role:
    name: dt-operator
  vars:
    dt_operator_release: "v1.2.3"
    operator_mode: "classicFullStack" 
```
