### ISSUE TITLE
[BUG] dt-edge-connect curated role deployment failure generate-credentials

### ISSUE THREAD

**Issue by IgnacioGoldman** [Dynatrace/ace-box#783]
dt-edge-connect role fails when deploying

```
- name: Generate credentials
  include_role:
    name: edge-connect
    tasks_from: generate-credentials
```

Role name should be:
`name: dt-edge-connect`
